apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2022-11-25T23:20:37Z"
  generation: 8
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-livelabs-perl-dancer
  name: perl-dancer
  namespace: livelabs
  resourceVersion: "2063448"
  uid: 796e6ae4-dcc1-4bec-9cfc-5c009aac46a5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-livelabs-perl-dancer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: perl
        workload.user.cattle.io/workloadselector: apps.deployment-livelabs-perl-dancer
    spec:
      affinity: {}
      containers:
      - env:
        - name: REDIS_SERVER
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: redis
              optional: false
        image: livelabs4linux/perl-dancer:latest
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-25T23:20:37Z"
    lastUpdateTime: "2022-11-26T23:34:22Z"
    message: ReplicaSet "perl-dancer-5d5669cfdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-11-26T23:35:14Z"
    lastUpdateTime: "2022-11-26T23:35:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
