apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2022-11-25T23:17:49Z"
  generation: 5
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-livelabs-redis
  name: redis
  namespace: livelabs
  resourceVersion: "2051678"
  uid: f6b14a1e-11a1-48e3-9f88-e640ba7f1c72
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-livelabs-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        workload.user.cattle.io/workloadselector: apps.deployment-livelabs-redis
    spec:
      affinity: {}
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: redis
              optional: false
        - name: REDIS_DISABLE_COMMANDS
          valueFrom:
            configMapKeyRef:
              key: redis_disable_commands
              name: redis
              optional: false
        image: docker.io/bitnami/redis:7.0
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: redis-disk
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: redis-disk
        persistentVolumeClaim:
          claimName: redis-disk
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-26T23:18:37Z"
    lastUpdateTime: "2022-11-26T23:18:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-11-25T23:17:49Z"
    lastUpdateTime: "2022-11-26T23:24:48Z"
    message: ReplicaSet "redis-79c4c86bfb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
