apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30635,"protocol":"TCP","serviceName":"livelabs:perl-dancer","allNodes":true}]'
  creationTimestamp: "2022-11-25T20:26:57Z"
  name: perl-dancer
  namespace: livelabs
  resourceVersion: "971513"
  uid: a0a5656e-fbd1-4fb4-a6b8-b2b726a24ea3
spec:
  clusterIP: 10.84.8.119
  clusterIPs:
  - 10.84.8.119
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: perl-port
    nodePort: 30635
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: perl
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
