apiVersion: v1
kind: Service
metadata:
  name: perl-dancer
  namespace: gitops
spec:
  ports:
  - name: perl-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: perl
  type: NodePort
