apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: livelabs
spec:
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
