apiVersion: v1
data:
  redis_password: NGxpbnV4
kind: Secret
metadata:
  creationTimestamp: "2022-11-25T20:09:10Z"
  name: redis
  namespace: livelabs
  resourceVersion: "959708"
  uid: f671bda0-35af-4786-aa50-92e943980ef6
type: Opaque
