apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: livelabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: redis
              optional: false
        - name: REDIS_DISABLE_COMMANDS
          valueFrom:
            configMapKeyRef:
              key: redis_disable_commands
              name: redis
        image: docker.io/bitnami/redis:7.0
        imagePullPolicy: Always
        name: container-0
