apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: perl
  name: perl-dancer
  namespace: livelabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: perl
    spec:
      containers:
      - env:
        - name: REDIS_SERVER
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: redis
        image: livelabs4linux/perl-dancer:latest
        imagePullPolicy: Always
        name: container-0
