apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30635,"protocol":"TCP","serviceName":"gitops:perl-dancer","allNodes":true}]'
  name: perl-dancer
  namespace: gitops
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: perl-port
    nodePort: 30635
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: perl
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
